### ISSUE TITLE
JS-DOS does not detect mouse clicks

### ISSUE THREAD

**Issue by teachjing** [DustinBrett/x#20]
keyboard input gets detected, but it seems the mouse input does not seem to detect. When I am comparing code with Dos.Zone, it looks like the emulator-mouse overlay fills up the whole screen. Use any mouse input game and you can replicate the issue. I was actually working on a right click menu when you already did it lol.

This does not seem to be the case in your setup. Possibly styling the CSS will fix this.

There are multiple elements and it seems that the focusClosestFocusableElementFromRef might be not routing the click to the right reference element? which needs to be the mouse overlay. 

Im thinking its related to how you setup dynamic stretching of the window.

**Comment by DustinBrett** [comment]
Hi @jingsta,

Thank you for looking into this! I will keep this in mind for my v2 version of the project which I am working on over at https://github.com/DustinBrett/x/tree/redo. I actually don't use `focusClosestFocusableElementFromRef` logic at the moment but it does indeed sound like you've found a bug in x v1.

I am hoping to release v2 of my project later this year which I hope will not have this issue you've mentioned. I will keep an eye on this and will keep this Issue open so I remember to not let this bug sneak into v2.

Thanks again!

**Comment by DustinBrett** [comment]
Closing v1 issues. Everything has been fully re-written.
