### ISSUE TITLE
can not type on msdos from mobile devices

### ISSUE THREAD

**Issue by deep5050** [DustinBrett/x#4]
currently it doesn't support typing on msdos app on mobile devices.
any plan on this?

Btw great work 😍

**Comment by DustinBrett** [comment]
Thanks for the feedback. Last night I upgraded to js-dos v7 which does have a virtual keyboard option. I haven't yet integrated it but this should be possible to do.

**Comment by YOYITsM3M8** [comment]
@DustinBrett Could there be a virtual controller for Doom and other games?

**Comment by DustinBrett** [comment]
Yes since upgrading to js-dos v7 last night that is now very possible. I'll be adding it shortly I hope.

**Comment by DustinBrett** [comment]
Closing v1 issues. Everything has been fully re-written.
