### ISSUE TITLE
Naming conflict

### ISSUE THREAD

**Issue by w3bb** [DustinBrett/x#7]
As a Unix user, I thought this related to the [X project](https://www.x.org).

**Comment by DustinBrett** [comment]
Yes the name x is partly inspired by x windows. Also it's just a letter and I partly used it out of lazyness, like variable x. Either way I'm gonna keep the name but thanks for the feedback.

**Comment by YOYITsM3M8** [comment]
> Yes the name x is partly inspired by x windows. Also it's just a letter and I partly used it out of lazyness, like variable x. Either way I'm gonna keep the name but thanks for the feedback.

i would name it z or y then
