### ISSUE TITLE
No instructions in the readme for installation

### ISSUE THREAD

**Issue by oregonpillow** [DustinBrett/x#8]
Any chance you could add a brief outline about how to deploy?
I'm new to web development and create websites and would love to try this project.

**Comment by YOYITsM3M8** [comment]
> Any chance you could add a brief outline about how to deploy?
> I'm new to web development and create websites and would love to try this project.

The way I would do it is to download node and npm. download this git repo, cd into it with your command line and do `npm i` this will install all of the dependencies needed. And finally `node .`

**Comment by DustinBrett** [comment]
Sure I will add something asap. For now I will just comment that this is a way you could deploy it:

Install dependencies: `npm i`
Build: `npm run build`
Export: `npm run export`

The `out` folder that is created can be hosted statically on a web server as a deploy option.

**Comment by k-u-sh** [comment]
Hey, so this is my first ever web development project and I was just really confused regarding the deployment: I did exactly what you said above and it did not work. I mean, I am only getting a timestamp on a blank page, and nothing else. I don't know what's going wrong or if I am missing anything, and I would be super grateful if you could maybe look into it for a bit!!

This may as well just be a very super dumb question and I may be missing out on something that I am supposed to do but have no idea of, but regardless, would be amazing if you can help me out here. (oh, and also I am referring to the index.html file here...so yeah)

Thanks a lot!! :D

Best,
Kush

**Comment by oregonpillow** [comment]
I have the exact same problem as @k-u-sh .

**Comment by DustinBrett** [comment]
I think this may be related to CNAME or something about hosting it that I haven't considered. I will try and find time in the next few days to figure out what's wrong and when I do I will comment here and update the docs with these deploy steps I've been promising. Thanks for the feedback guys.

**Comment by DustinBrett** [comment]
Closing v1 issues. Everything has been fully re-written.
